-- MySQL Script generated by MySQL Workbench
-- qui 18 set 2025 15:41:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stock_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `stock_db` ;

-- -----------------------------------------------------
-- Table `stock_db`.`item_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock_db`.`item_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `stock_db`.`stock_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock_db`.`stock_item` (
  `category_id` INT NOT NULL,
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(38,2) NOT NULL,
  `quantity` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`item_id`),
  INDEX `FK97dbtx8jt6xc2qeuh1igkv1jm` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK97dbtx8jt6xc2qeuh1igkv1jm`
    FOREIGN KEY (`category_id`)
    REFERENCES `stock_db`.`item_category` (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
